### ISSUE TITLE
Custom Prize Strategy

### ISSUE THREAD

**Issue by sirgawain0x** [g2entgroup/pool-contracts#3]
Prize Strategy
There will be two rounds of votes 🗳

Fans will vote down to the top 10 submissions.

Raffle tickets for the final minted NFT 🎟 will be distributed randomly to fans who voted for the submission winner(s).

1:1 distribution 

1 NFT per submission creator winner, 
1 NFT to brand, 
remaining minted NFTs will go to fan winners.

**Comment by georgeroman** [comment]
To have something to build upon I think we might first need to have the CRTVO token in place together with the voting mechanism. Once this is done, our custom MultipleWinnersStrategy could simply pull the winners from the voting results.

**Comment by georgeroman** [comment]
@gawainb I would like to get started on the voting mechanism. Some questions:
- what does a submission represent in this case (so we know how to encoded it on-chain)
- how does voting works (is it in proportion to the tokens an address owns or is it one vote per address regardless of the number of tokens the address owns)
- what should happen in case of ties (should the voting restart or should it get extended)

**Comment by sirgawain0x** [comment]
@georgeroman @Stevewu1234 

- A submission would consist of both: NFT (erc721) and CRTV (erc20)
_Creators would deposit (erc20) 10% of the brands deposit amount_

- The voting mechanism will require this repo @lidachao111222 [Creative Governance UI](https://github.com/g2entgroup/creative-governance)
- https://github.com/pooltogether/documentation/blob/master/governance/overview.md
_Voting would be basically be users would stake to vote (the percentage we have to discuss) for the top 10. While those users are staking and voting, my thoughts are to allow those fans to earn (social tokens) from the creator they voted for. At the end of the campaign the stakers would receive their (erc20) back._

- Ties would start a new vote period for fans to vote and break those specific ties.
- Brands would select the winner from the top 10.

**Comment by sirgawain0x** [comment]
@georgeroman looks like there are new updates around Aave now that they are available on Polygon, I'll push these in tonight for us. https://github.com/pooltogether/aave-yield-source/pull/7
